[pytest]
addopts = -q -p no:cacheprovider --import-mode=importlib
pythonpath = . backend
testpaths =
    tests
    modules/bar/tests
    modules/plugins/tests
    modules/menu/tests
    modules/defaults/tests
    modules/monitors/tests
    modules/themes/tests
    modules/keybindings/tests
    modules/modes/tests
