-- Generated by Omarchy Customization Center. Do not edit; the next apply overwrites this file.
-- profile: laptop
-- profileDigest: sha256:95a48220db2739c6c6bac82b31b0b661abbf4e6ad5e26dfc04d5eec60ab52e2e
-- confirmBy: 1767225780
if os.time() > 1767225780 then return end
hl.monitor({ output = "desc:Laptop Panel", mode = "2880x1800@60", position = "0x0", scale = 2, transform = 0 })
