from __future__ import annotations

import hashlib
import json
from typing import Any

from customization_center.core import lua_string

_HEADER = "-- Generated by Omarchy Customization Center. Do not edit; the next apply overwrites this file."
NOOP = "-- Generated by Omarchy Customization Center. No monitor profile is active.\n"


def _number(value: int, divisor: int, places: int) -> str:
    return f"{value / divisor:.{places}f}".rstrip("0").rstrip(".")


def digest(profile: dict[str, Any]) -> str:
    payload = json.dumps(profile, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()
    return "sha256:" + hashlib.sha256(payload).hexdigest()


def render(profile: dict[str, Any], assignments: dict[str, str], connected: list[dict[str, Any]], confirm_by: int | None = None) -> str:
    by_connector = {item["connector"]: item for item in connected}
    descriptions = [item.get("description", "") for item in connected if item.get("description")]
    by_id = {item["id"]: item for item in profile["outputs"]}
    def selector(rule: dict[str, Any]) -> str:
        connector = assignments[rule["id"]]; description = by_connector[connector].get("description", "")
        unique = description and sum(1 for item in descriptions if description in item or item in description) == 1
        return "desc:" + description if unique else connector
    def key(rule: dict[str, Any]) -> tuple[Any, ...]:
        if not rule["enabled"]: return (2, rule["id"])
        if rule.get("mirrorOf"): return (1, rule["id"])
        position = rule["position"]; return (0, position["x"], position["y"], rule["id"])
    lines = [_HEADER, f"-- profile: {profile['id']}", f"-- profileDigest: {digest(profile)}"]
    if confirm_by is not None:
        lines.extend([f"-- confirmBy: {confirm_by}", f"if os.time() > {confirm_by} then return end"])
    for rule in sorted((item for item in profile["outputs"] if item["id"] in assignments), key=key):
        fields = ["output = " + lua_string(selector(rule))]
        if not rule["enabled"]:
            fields.append("disabled = true")
        else:
            mode = rule["mode"]
            fields.extend(["mode = " + lua_string(f"{mode['width']}x{mode['height']}@{_number(mode['refreshMilliHz'], 1000, 3)}"),
                           "position = " + lua_string("0x0" if rule.get("mirrorOf") else f"{rule['position']['x']}x{rule['position']['y']}"),
                           "scale = " + _number(rule["scale120"], 120, 6), f"transform = {rule['transform']}"])
            if rule.get("bitDepth") is not None: fields.append(f"bitdepth = {rule['bitDepth']}")
            if rule.get("vrr") is not None: fields.append(f"vrr = {rule['vrr']}")
            if rule.get("mirrorOf"):
                fields.append("mirror = " + lua_string(assignments[rule["mirrorOf"]]))
        lines.append("hl.monitor({ " + ", ".join(fields) + " })")
    extra = profile.get("extraOutputs")
    if extra:
        scale = lua_string("auto") if extra["scale"] == "auto" else _number(extra["scale"], 120, 6)
        lines.append("hl.monitor({ output = \"\", mode = " + lua_string(extra["mode"]) + ", position = " + lua_string(extra["position"]) + ", scale = " + scale + " })")
    return "\n".join(lines) + "\n"
